### ISSUE TITLE
How to integrate with Puppeteer?

### ISSUE THREAD

**Issue by acotilla91** [transitive-bullshit/captcha-solver#4]
This seems like an amazing tool but I'm having issues integrating it with Puppeteer. Are there any examples available on how to achieve this. Thanks!

**Comment by transitive-bullshit** [comment]
This is a great question.

Here is an [example](https://github.com/transitive-bullshit/puppeteer-email/blob/master/packages/puppeteer-email-provider-outlook/lib/signup.js#L236-L291) of using `captcha-solver` with Outlook's signup flow.

**Comment by acotilla91** [comment]
Awesome. Thanks!
