### ISSUE TITLE
How to solve this captcha

### ISSUE THREAD

**Issue by Thalisson** [transitive-bullshit/captcha-solver#6]
I tried many method it didn't work, can u help me for this? Many thanks!

![1](https://user-images.githubusercontent.com/3827329/48815168-a1906300-ed24-11e8-9c1f-d73786bfd74c.png)

![2](https://user-images.githubusercontent.com/3827329/48815169-a228f980-ed24-11e8-9899-6db68614bc1f.png)

![3](https://user-images.githubusercontent.com/3827329/48815170-a228f980-ed24-11e8-8d55-fe0dad27d2c6.png)

![4](https://user-images.githubusercontent.com/3827329/48815171-a228f980-ed24-11e8-9def-7d2ebc32df06.png)

![5](https://user-images.githubusercontent.com/3827329/48815172-a228f980-ed24-11e8-8ddb-29bf10af2836.png)

![6](https://user-images.githubusercontent.com/3827329/48815173-a228f980-ed24-11e8-8296-5d006786d92b.png)

**Comment by Thalisson** [comment]
> I tried many method it didn't work, can u help me for this? Many thanks!
> 
> ![1](https://user-images.githubusercontent.com/3827329/48815168-a1906300-ed24-11e8-9c1f-d73786bfd74c.png)
> 
> ![2](https://user-images.githubusercontent.com/3827329/48815169-a228f980-ed24-11e8-9899-6db68614bc1f.png)
> 
> ![3](https://user-images.githubusercontent.com/3827329/48815170-a228f980-ed24-11e8-8d55-fe0dad27d2c6.png)
> 
> ![4](https://user-images.githubusercontent.com/3827329/48815171-a228f980-ed24-11e8-9def-7d2ebc32df06.png)
> 
> ![5](https://user-images.githubusercontent.com/3827329/48815172-a228f980-ed24-11e8-8ddb-29bf10af2836.png)
> 
> ![6](https://user-images.githubusercontent.com/3827329/48815173-a228f980-ed24-11e8-8296-5d006786d92b.png)

**Comment by milad145** [comment]
hi @Thalisson 
do you know how to work with this module?
